<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="thrymr-To-be-filled-by-O-E-M" name="Default test(failed)" tests="1" failures="1" timestamp="31 Dec 2019 07:55:56 GMT" time="0.003" errors="0">
  <testcase name="tearDown" time="0.001" classname="com.testng.poc.TestCase1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.testng.poc.TestCase1.tearDown(TestCase1.java:30)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- tearDown -->
</testsuite> <!-- Default test(failed) -->
