<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="thrymr-To-be-filled-by-O-E-M" name="Test(failed)(failed)(failed)" tests="1" failures="1" timestamp="31 Dec 2019 10:01:37 GMT" time="0.022" errors="0">
  <testcase name="tearDown" time="0.008" classname="com.testng.poc.TestCase1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.testng.poc.TestCase1.tearDown(TestCase1.java:30)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tearDown -->
</testsuite> <!-- Test(failed)(failed)(failed) -->
